--Funções de tempo

--Diferença entre Date E Datetime

--GETDATE()
SELECT GETDATE()
--DATEDIFF()
SELECT DATEDIFF(YEAR, '2001-11-14', GETDATE())
--DATEADD()
SELECT DATEADD(MONTH, -1, GETDATE())

SELECT DATEADD(MONTH, -1, DATEADD(YEAR, -1, GETDATE()))
--DATEPART()
SELECT DATEPART(WEEKDAY, DATEADD(YEAR, -1, GETDATE()))
--BETWEEN()
SELECT * FROM tb_vendas WHERE dtVenda BETWEEN DATEADD(YEAR, -1, GETDATE()) AND GETDATE()
--FORMAT()
SELECT CAST(GETDATE() AS DATE)

SELECT FORMAT(CAST(GETDATE() AS DATE), 'dd/MM/yyyy')

SELECT * FROM tb_vendas WHERE dtVenda >= FORMAT(GETDATE(), '01/MM/yyyy')